user_pref("mailnews.default_news_sort_order", 2);
user_pref("mailnews.default_news_sort_type", 18);
user_pref("mailnews.default_sort_type", 18);
user_pref("mailnews.default_sort_order", 2);
user_pref("mailnews.default_view_flags", 0);
user_pref("beacon.enabled", false);
user_pref("browser.display.use_document_fonts", 0);
user_pref("font.language.group", "x-western");
user_pref("font.name.monospace.x-western", "Noto Sans");
user_pref("font.size.monospace.x-western", 22);
user_pref("mail.uifontsize", 17);
user_pref("mail.close_message_window.on_delete", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("app.donation.eoy.version.viewed", "999");
