#!/usr/bin/env bash
target=$1
if [[ $(nmcli con show --active | grep "${target}") ]]; then
    echo Active, deactivating
    nmcli con down "${target}"
else
    echo Not active, activating
    nmcli con up "${target}"
fi
