#!/usr/bin/env @bash@/bin/bash
action=$1

save_brightness () {
    @brightnessctl@/bin/brightnessctl g > /tmp/last_brightness
}
dim_screen () {
    DISPLAY=:0 @libnotify@/bin/notify-send -t 2000 "Zzzzz"
    DISPLAY=:0 @awesome@/bin/awesome-client 'flash_toggle(client.focus)'
    @coreutils@/bin/coreutils --coreutils-prog=sleep 2
    DISPLAY=:0 @awesome@/bin/awesome-client 'flash_toggle(client.focus)'
    @brightnessctl@/bin/brightnessctl s 20
}
screen_off () {
    DISPLAY=:0 @xset@/bin/xset dpms force off
}
screen_on () {
    DISPLAY=:0 @xset@/bin/xset dpms force on
    DISPLAY=:0 @xset@/bin/xset -dpms
}

restore_brightness () {
    @brightnessctl@/bin/brightnessctl s `@coreutils@/bin/coreutils --coreutils-prog=cat /tmp/last_brightness`
}

lock_screen () {
    /run/wrappers/bin/sudo @slock@/bin/slock
}

if [[ "$action" == "start" ]]; then
    # Check if it's already locked and do nothing
    [[ `@procps@/bin/pidof slock` ]] && exit

    save_brightness
    dim_screen

elif [[ "$action" == "cancel" ]]; then
    screen_on
    if test -f "/tmp/last_brightness"; then
        restore_brightness
    fi

elif [[ "$action" == "lock" ]]; then
    screen_off
    lock_screen
fi
