#!/usr/bin/env python3

from sys import argv
from PyP100 import PyP100

p100 = PyP100.P100(argv[1], argv[2], argv[3])

p100.handshake()
p100.login()

if p100.getDeviceInfo()['result']['device_on']:
    p100.turnOff()
else:
    p100.turnOn()
